# These are supported funding model platforms

github: #
patreon: MorrowShore
open_collective: #
ko_fi: MorrowShore
tidelift: #
community_bridge: #
liberapay: #
issuehunt: #
otechie: #
lfx_crowdfunding: #
custom: https://morrowshore.com/store/
